[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[metadata]
name = "ConcurrentDatabase"
author = "Jay S"
description = "A simple sql wrapper for making a database be object oriented"

[options]
packages = find:
install_requires = ["sqlite3", "loguru"]